### ISSUE TITLE
Emacs config TODO

### ISSUE THREAD

**Issue by CarlosMChica** [PaNaVTEC/dotfiles#8]
- [x] React
- [x] Padding line numbers
- [x] When increasing font size line numbers doesn't scale
- [x] | cursor insert mode cli
- [x] Cool theme take a look at: https://github.com/Greduan/emacs-theme-gruvbox , Doom theme, etc...
- [ ] Icons neotree
- [ ] Icons powerline
- [x] Split config into files
- [x] Prettify symbols in js
- [x] Prettify symbols in haskell
- [x] Keybinding to toggle between dark/light themes: https://emacs.stackexchange.com/questions/24088/make-a-function-to-toggle-themes#26981
- [x] Hot reload configuration
- [x] Emacs as a daemon
- [x] Undo persistent between sessions
- [x] Diminish / delight modes in the modeline: https://github.com/Otann/emacs.d/blob/19034178cd0d18ab946217dbc461d0979fff7b0e/configuration-modules/otann-ide.el#L348
- [x] Copy from emacs to clipboard - http://blog.binchen.org/posts/copypaste-in-emacs.html
- [x] no confirm when following a symlink
- [x] Git gutter with keybindings
- [x] Javascript indentation does not work
- [x] Show hidden files in neotree by default
- [x] Rainbow parentesys
- [x] Customise undo history dir
- [x] Neotree interactive menu to add/delete/modify nodes
- [x] :wqa write-quit-all
- [x] Gutter mode enabled by default and disabled in files where it's useless 
- [ ] Bind keys for merge: https://emacs.stackexchange.com/questions/16469/how-to-merge-git-conflicts-in-emacs
- [x] Control in which buffer helm gets open while doing Ctrlp
- [x] ctrl-z to suspend emacs
- [x] magit
- [ ] Indium for JS https://github.com/NicolasPetton/Indium
- [ ] Neotree help does not work. It should show Press ? for help at the top of the neotree buffer but it doesn't. Actually pressing ? to show help does not work either
- [ ] Add Java config: https://github.com/mopemope/meghanada-emacs
- [x] AG
- [x] Load configuration per file type (https://github.com/PaNaVTEC/dotfiles/commit/cb44be65418496f48a3d86f3f88fb87340751918)

**Comment by PaNaVTEC** [comment]
Cursor mode: https://github.com/PaNaVTEC/dotfiles/commit/3afe352e7a35fe7aba569f6e180779fa44030762

**Comment by PaNaVTEC** [comment]
Padding line numbers: https://github.com/PaNaVTEC/dotfiles/commit/24912ca1ea4b1287256989ca790d6eb2042d572e

This seems to fix "When increasing font size line numbers doesn't scale" as well :tada:

**Comment by PaNaVTEC** [comment]
React + standardjs flycheck: https://github.com/PaNaVTEC/dotfiles/commit/972d5aee77b2369f051998be203111e67d4bd4ea

**Comment by PaNaVTEC** [comment]
Split into files: https://github.com/PaNaVTEC/dotfiles/commit/463298f8286f02948aaa69fba2be123b98eb1203

**Comment by CarlosMChica** [comment]
Peristent undo history: https://github.com/CarlosMChica/dotfiles/commit/cbd4e9defa831b65d9f76d3ff7b49969f8de7e7a

**Comment by PaNaVTEC** [comment]
Git gutter: https://github.com/PaNaVTEC/dotfiles/commit/e53afae6f83dd5b7a2923556997b596c616b7757

**Comment by CarlosMChica** [comment]
Show hidden files in neotree by default https://github.com/CarlosMChica/dotfiles/commit/7ec8510be39e378aa98c3573ff3380f9ea4af3d1

**Comment by CarlosMChica** [comment]
Customise undo history dir https://github.com/CarlosMChica/dotfiles/commit/646c1cc52f23fe304a06f05d7a670c8826cb1dc5

**Comment by PaNaVTEC** [comment]
Wqa https://github.com/PaNaVTEC/dotfiles/commit/6b264fd7a4a11780279ea1442cfae16c1cd2a25d

**Comment by PaNaVTEC** [comment]
follow symlinks: https://github.com/PaNaVTEC/dotfiles/commit/c5dbbdb41fb82c8886a79170b2574caa92af60c7

**Comment by PaNaVTEC** [comment]
Neotree menu: 
https://github.com/PaNaVTEC/dotfiles/commit/d7af3e64637dd7ada3f74e5005446cc6e5e6e205
https://github.com/PaNaVTEC/dotfiles/commit/f69c855cb2d31d79ab81331a5ee53cb9cd8e2f38

**Comment by PaNaVTEC** [comment]
Minor mode for relative numbers/git-gutter: https://github.com/PaNaVTEC/dotfiles/commit/a637d2c349d0f25664df32d88926c61bdeef4eef

**Comment by CarlosMChica** [comment]
Emacs -> Clipboard https://github.com/CarlosMChica/dotfiles/commit/ae7f43902b12bbf945ffe2bec0220416f8402c9d

**Comment by PaNaVTEC** [comment]
I'm closing this as is mostly implemented
